version: '3'
services:
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - 6379:6379
    networks:
      - mynetwork

  sensor-generator:
    build:
      context: .
    command: bash -c "ls -la && poetry run python /app/sensor-generator.py"
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
